require('dotenv').config()
const express = require('express')
const app = express()
const bodyParser = require('body-parser')
const morgan = require('morgan')
const userRouter = require('./route/user')
const boardRouter = require('./route/board')
const commendRouter = require('./route/commend')
const connectDB = require('./config/database')
connectDB()
// middleware
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended : false}))
app.use(morgan('dev'))
// require route
app.use('/user', userRouter)
app.use('/board', boardRouter)
app.use('/commend', commendRouter)
const PORT = process.env.PORT || 7000
app.listen(PORT, console.log("connected server..."))